import {spawn} from 'node:child_process';
import {mkdtemp, rm, writeFile, mkdir} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const profile=await mkdtemp(path.join(os.tmpdir(),'srok-capture-'));
const port=39500+Math.floor(Math.random()*500);
const chrome=process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const game=pathToFileURL(path.join(root,'app','src','main','assets','index.html')).href;
const proc=spawn(chrome,[`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'--headless=new','--disable-gpu','--no-sandbox',game],{stdio:'ignore'});
let ws,seq=0;
const pending=new Map();
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function call(method,params={}) {
  const id=++seq;
  const result=new Promise((resolve,reject)=>pending.set(id,{resolve,reject}));
  ws.send(JSON.stringify({id,method,params}));
  const response=await result;
  if(response.error)throw new Error(response.error.message);
  return response.result;
}
try {
  let target;
  for(let i=0;i<50;i++){
    try {target=(await (await fetch(`http://127.0.0.1:${port}/json`)).json()).find(page=>page.type==='page');if(target)break;}catch(_){}
    await delay(100);
  }
  if(!target)throw new Error('Chrome did not start');
  ws=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  ws.onmessage=event=>{const data=JSON.parse(event.data);if(!data.id)return;const task=pending.get(data.id);if(task){pending.delete(data.id);task.resolve(data);}};
  await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await call('Page.reload');
  await delay(800);
  await mkdir(path.join(root,'qa'),{recursive:true});
  const welcome=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','welcome-mobile.png'),Buffer.from(welcome.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('close')"});
  const screen=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','farm-mobile.png'),Buffer.from(screen.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('language')"});
  const khmer=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','farm-khmer.png'),Buffer.from(khmer.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('openMini','lotus')"});
  const lotusKhmer=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','lotus-mini-khmer.png'),Buffer.from(lotusKhmer.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('close')"});
  await call('Runtime.evaluate',{expression:"SrokGame.act('openMini','rice')"});
  const rice=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','rice-mini-khmer.png'),Buffer.from(rice.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('close'); SrokGame.act('language'); (()=>{const s=SrokGame.getState();s.xp=220;s.inventory.cotton=3;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s))})()"});
  await call('Page.reload');
  await delay(600);
  await call('Runtime.evaluate',{expression:"SrokGame.act('farmMode','games')"});
  const gamesHub=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','games-hub-mobile.png'),Buffer.from(gamesHub.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('openMini','fish')"});
  const fish=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','fish-mini-mobile.png'),Buffer.from(fish.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('close'); SrokGame.act('openMini','cargo')"});
  const cargo=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','cargo-mini-mobile.png'),Buffer.from(cargo.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('close'); SrokGame.act('openMini','recipe')"});
  await delay(350);
  const recipe=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','recipe-mini-mobile.png'),Buffer.from(recipe.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('close')"});
  await call('Runtime.evaluate',{expression:"SrokGame.act('tab','kitchen'); SrokGame.act('kitchenMode','workshop'); SrokGame.act('openMini','loom')"});
  const loom=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','loom-mini-mobile.png'),Buffer.from(loom.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('tab','market'); SrokGame.act('openMini','market')"});
  const market=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','market-mini-mobile.png'),Buffer.from(market.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('close')"});
  const marketScreen=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','market-mobile.png'),Buffer.from(marketScreen.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('tab','farm'); SrokGame.act('openMini','lotus')"});
  const lotus=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','lotus-mini-mobile.png'),Buffer.from(lotus.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('close'); SrokGame.act('openMini','canal')"});
  const canal=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','canal-mini-mobile.png'),Buffer.from(canal.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('close'); (()=>{const s=SrokGame.getState();s.xp=700;s.coins=2400;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()"});
  await delay(650);
  await call('Runtime.evaluate',{expression:"SrokGame.act('buyProperty','family_home'); SrokGame.act('buyProperty','produce_truck'); SrokGame.act('tab','journal'); document.querySelector('.property-head').scrollIntoView({block:'start'})"});
  await delay(3500);
  const property=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','village-property-mobile.png'),Buffer.from(property.data,'base64'));
  await call('Runtime.evaluate',{expression:"SrokGame.act('tab','explore')"});
  await delay(200);
  const explore=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(path.join(root,'qa','explore-hd-mobile.png'),Buffer.from(explore.data,'base64'));
  console.log('Saved phone previews for the farm, Games hub, eight mini games, market, property, and HD scenery in qa/');
} finally {
  if(ws)ws.close();
  proc.kill();
  await rm(profile,{recursive:true,force:true,maxRetries:3,retryDelay:150});
}
