import {spawn} from 'node:child_process';
import {mkdtemp, rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const html=path.join(root,'app','src','main','assets','index.html');
const chrome=process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const profile=await mkdtemp(path.join(os.tmpdir(),'srok-smoke-'));
const port=39000+Math.floor(Math.random()*5000);
const processChrome=spawn(chrome,[`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'--headless=new','--disable-gpu','--no-sandbox',pathToFileURL(html).href],{stdio:'ignore'});
let ws,seq=0;
const pending=new Map();
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function evalJs(expression) {
  const id=++seq;
  const result=new Promise((resolve,reject)=>pending.set(id,{resolve,reject}));
  ws.send(JSON.stringify({id,method:'Runtime.evaluate',params:{expression,returnByValue:true,awaitPromise:true}}));
  const msg=await result;
  if(msg.result.exceptionDetails) throw new Error(msg.result.exceptionDetails.text);
  return msg.result.result.value;
}
async function waitForGame(){for(let i=0;i<40;i++){try{if(await evalJs('typeof SrokGame !== "undefined"'))return;}catch(_){}await pause(100);}throw new Error('Game did not load');}
function assert(condition,message){if(!condition)throw new Error(message);}
try {
  let target;
  for(let i=0;i<50;i++) {try {const pages=await (await fetch(`http://127.0.0.1:${port}/json`)).json();target=pages.find(p=>p.type==='page');if(target)break;}catch(_){}await pause(100);}
  if(!target)throw new Error('Chrome did not start');
  ws=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  ws.onmessage=e=>{const msg=JSON.parse(e.data);if(!msg.id)return;const p=pending.get(msg.id);if(p){pending.delete(msg.id);p.resolve(msg);}};
  await waitForGame();
  assert(await evalJs('!!document.querySelector("#farm-map .map-plot")'),'Farm map did not render');
  assert((await evalJs('document.querySelectorAll("#farm-map .map-plot").length'))===20,'Farm map plots missing');
  await evalJs("SrokGame.act('mapZoom','in')");
  assert((await evalJs('SrokGame.getState().mapCamera.zoom'))>1,'Map zoom failed');
  await evalJs("SrokGame.act('farmMode','fields')");
  assert((await evalJs('document.querySelectorAll(".fields .plot").length'))===12,'Field grid fallback missing');
  await evalJs("SrokGame.act('farmMode','map')");
  await evalJs("SrokGame.act('close'); document.querySelector('.map-plot[data-id=\"0\"]').click()");
  assert((await evalJs('SrokGame.getState().plots[0].id'))==='rice','Rice planting failed');
  await evalJs('Date.now=()=>new Date().getTime()+30000');
  await evalJs("SrokGame.act('plot','0'); SrokGame.act('fish')");
  assert((await evalJs('SrokGame.getState().inventory.rice'))===2,'Rice harvest failed');
  assert((await evalJs('SrokGame.getState().inventory.fish'))===1,'Fishing failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.version=2;delete s.travel;delete s.visits;delete s.cookedKinds;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert((await evalJs('SrokGame.getState().version'))===5,'Existing save migration failed');
  assert((await evalJs('SrokGame.getState().inventory.rice'))===2,'Existing inventory was lost');
  await evalJs(`(()=>{const s=SrokGame.getState();s.chapter=4;s.decor=['flowers','lanterns','boat'];s.coins=250;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert(await evalJs('SrokGame.chapterComplete()'),'Festival goal did not register');
  await evalJs("SrokGame.act('claim')");
  const final=await evalJs('SrokGame.getState()');
  assert(final.won&&final.chapter===5&&final.coins===50,'Festival completion failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.xp=650;s.coins=300;s.lastDaily='';localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  await evalJs("SrokGame.act('daily'); SrokGame.act('trip','tonle_sap')");
  assert((await evalJs('SrokGame.getState().coins'))===330,'Daily reward or free trip failed');
  await evalJs('Date.now=()=>new Date().getTime()+100000');
  await evalJs("SrokGame.act('collectTrip')");
  assert((await evalJs('SrokGame.getState().visits.tonle_sap'))===1,'Trip collection failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.inventory.pepper=2;s.inventory.crab=1;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  await evalJs("SrokGame.act('cook','pepper_crab')");
  assert((await evalJs('SrokGame.getState().cookedKinds.pepper_crab'))===1,'Regional recipe failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.journeyChapter=3;s.visits={tonle_sap:2,kep:2,kampong_speu:2,mondulkiri:2};s.stats.trips=8;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert(await evalJs('SrokGame.journeyComplete()'),'Journey goal did not register');
  await evalJs("SrokGame.act('journeyClaim')");
  assert((await evalJs('SrokGame.getState().journeyWon'))===true,'River celebration failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.xp=650;s.coins=1000;s.fishAt=0;s.plots[0]=null;s.travel=null;s.upgrades=[];s.inventory.rice=2;s.inventory.fish=1;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  const fishBefore=await evalJs('SrokGame.getState().inventory.fish');
  await evalJs("SrokGame.act('upgrade','net'); SrokGame.act('fish')");
  assert((await evalJs('SrokGame.getState().inventory.fish'))===fishBefore+2,'Fishing net upgrade failed');
  await evalJs("SrokGame.act('upgrade','irrigation'); SrokGame.act('plot','0')");
  assert((await evalJs('SrokGame.getState().plots[0].at-Date.now()'))<20000,'Irrigation upgrade failed');
  await evalJs("SrokGame.act('upgrade','cart'); SrokGame.act('trip','kep')");
  assert((await evalJs('SrokGame.getState().travel.at-Date.now()'))<54000,'Travel cart upgrade failed');
  const porridgeBefore=await evalJs('SrokGame.getState().inventory.porridge || 0');
  await evalJs("SrokGame.act('upgrade','stove'); SrokGame.act('cook','porridge')");
  assert((await evalJs('SrokGame.getState().inventory.porridge'))===porridgeBefore+2,'Clay stove upgrade failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.version=3;s.coins=1000;s.xp=650;s.inventory.rice=8;s.inventory.fish=3;s.plots=s.plots.slice(0,12);delete s.workshop;delete s.craftedKinds;delete s.friendship;delete s.giftAt;delete s.makersChapter;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert((await evalJs('SrokGame.getState().version'))===5,'Version 1.1 save migration failed');
  await evalJs("SrokGame.act('expand'); SrokGame.act('expand')");
  assert((await evalJs('SrokGame.getState().plots.length'))===20,'Field expansion failed');
  await evalJs("SrokGame.act('craft','rice_flour')");
  assert((await evalJs('SrokGame.getState().workshop.id'))==='rice_flour','Workshop start failed');
  await evalJs('Date.now=()=>new Date().getTime()+50000');
  await evalJs("SrokGame.act('collectCraft')");
  assert((await evalJs('SrokGame.getState().craftedKinds.rice_flour'))===1,'Workshop collection failed');
  await evalJs("SrokGame.act('gift','dara')");
  assert((await evalJs('SrokGame.getState().friendship.dara'))===1,'Friendship gift failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.inventory.cotton=3;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  await evalJs("SrokGame.act('craft','krama')");
  await evalJs('Date.now=()=>new Date().getTime()+100000');
  await evalJs("SrokGame.act('collectCraft')");
  assert((await evalJs('SrokGame.getState().craftedKinds.krama'))===1,'Krama crafting failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.makersChapter=2;s.stats.crafted=10;s.stats.gifts=10;s.friendship.dara=10;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert(await evalJs('SrokGame.makersComplete()'),'Makers goal did not register');
  await evalJs("SrokGame.act('makersClaim')");
  assert((await evalJs('SrokGame.getState().makersWon'))===true,'Makers fair ending failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.decor=['flowers'];s.decorPositions={flowers:{x:340,y:345}};localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert(await evalJs('document.querySelector(".map-decoration").style.left==="340px"'),'Saved decoration position missing');
  assert((await evalJs('SrokGame.getState().mapCamera.zoom'))>1,'Saved map zoom was lost');
  await evalJs("SrokGame.act('arrange'); document.querySelector('.map-decoration').click()");
  assert(await evalJs('document.querySelector(".map-decoration").classList.contains("selected")'),'Decoration selection failed');
  await evalJs(`(()=>{const v=document.querySelector('#farm-map'),r=v.getBoundingClientRect();document.querySelector('#map-world').dispatchEvent(new MouseEvent('click',{bubbles:true,clientX:r.left+60,clientY:r.top+90}))})()`);
  assert((await evalJs('SrokGame.getState().decorPositions.flowers.x'))!==340,'Decoration placement failed');
  console.log('PASS: old-save migration, farming, travel, upgrades, workshop, krama, friendships, field expansion, three endings');
} finally {
  if(ws)ws.close();
  processChrome.kill();
  if(profile.startsWith(os.tmpdir()+path.sep))await rm(profile,{recursive:true,force:true,maxRetries:3,retryDelay:150});
}
