import {spawn} from 'node:child_process';
import {mkdtemp, rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const html=path.join(root,'app','src','main','assets','index.html');
const chrome=process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const profile=await mkdtemp(path.join(os.tmpdir(),'srok-smoke-'));
const port=39000+Math.floor(Math.random()*5000);
const processChrome=spawn(chrome,[`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'--headless=new','--disable-gpu','--no-sandbox',pathToFileURL(html).href],{stdio:'ignore'});
let ws,seq=0;
const pending=new Map();
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function evalJs(expression) {
  const id=++seq;
  const result=new Promise((resolve,reject)=>pending.set(id,{resolve,reject}));
  ws.send(JSON.stringify({id,method:'Runtime.evaluate',params:{expression,returnByValue:true,awaitPromise:true}}));
  const msg=await result;
  if(msg.result.exceptionDetails) throw new Error(msg.result.exceptionDetails.exception?.description||msg.result.exceptionDetails.text);
  return msg.result.result.value;
}
async function waitForGame(){for(let i=0;i<40;i++){try{if(await evalJs('typeof SrokGame !== "undefined"'))return;}catch(_){}await pause(100);}throw new Error('Game did not load');}
function assert(condition,message){if(!condition)throw new Error(message);}
async function completeFish(){
  for(let i=0;i<3;i++)await evalJs("document.querySelector('.mini-fish-tile.fish').click()");
}
try {
  let target;
  for(let i=0;i<50;i++) {try {const pages=await (await fetch(`http://127.0.0.1:${port}/json`)).json();target=pages.find(p=>p.type==='page');if(target)break;}catch(_){}await pause(100);}
  if(!target)throw new Error('Chrome did not start');
  ws=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  ws.onmessage=e=>{const msg=JSON.parse(e.data);if(!msg.id)return;const p=pending.get(msg.id);if(p){pending.delete(msg.id);p.resolve(msg);}};
  await waitForGame();
  await evalJs("SrokGame.act('startTutorial')");
  assert((await evalJs('SrokGame.getState().tutorialStep'))===1,'Guided tutorial did not start');
  assert(await evalJs('!!document.querySelector("#farm-map .map-plot")'),'Farm map did not render');
  assert((await evalJs('document.querySelectorAll("#farm-map .map-plot").length'))===20,'Farm map plots missing');
  await evalJs("SrokGame.act('mapZoom','in')");
  assert((await evalJs('SrokGame.getState().mapCamera.zoom'))>1,'Map zoom failed');
  await evalJs("SrokGame.act('farmMode','fields')");
  assert((await evalJs('document.querySelectorAll(".fields .plot").length'))===12,'Field grid fallback missing');
  await evalJs("SrokGame.act('farmMode','map')");
  await evalJs("SrokGame.act('close'); document.querySelector('.map-plot[data-id=\"0\"]').click(); SrokGame.act('plantChosen','rice')");
  assert((await evalJs('SrokGame.getState().plots[0].id'))==='rice','Rice planting failed');
  assert((await evalJs('SrokGame.getState().tutorialStep'))===2,'Tutorial planting step failed');
  const startingFish=await evalJs('SrokGame.getState().inventory.fish || 0');
  await evalJs('Date.now=()=>new Date().getTime()+30000');
  await evalJs("SrokGame.act('plot','0'); SrokGame.act('fishPanel'); SrokGame.act('fishCast')");
  await evalJs('Date.now=()=>new Date().getTime()+33000');
  await evalJs("SrokGame.act('fishCatch')");
  assert((await evalJs('SrokGame.getState().inventory.fish || 0'))===startingFish,'Fish was awarded before the catch game');
  await completeFish();
  assert((await evalJs('SrokGame.getState().inventory.rice'))===2,'Rice harvest failed');
  assert((await evalJs('SrokGame.getState().tutorialStep'))===3,'Tutorial harvest step failed');
  assert((await evalJs('SrokGame.getState().inventory.fish'))===startingFish+1,'Fishing failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.version=2;delete s.travel;delete s.visits;delete s.cookedKinds;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert((await evalJs('SrokGame.getState().version'))===9,'Existing save migration failed');
  assert((await evalJs('SrokGame.getState().inventory.rice'))===2,'Existing inventory was lost');
  await evalJs(`(()=>{const s=SrokGame.getState();s.chapter=4;s.decor=['flowers','lanterns','boat'];s.coins=250;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert(await evalJs('SrokGame.chapterComplete()'),'Festival goal did not register');
  await evalJs("SrokGame.act('claim')");
  const final=await evalJs('SrokGame.getState()');
  assert(final.won&&final.chapter===5&&final.coins===50,'Festival completion failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.xp=650;s.coins=300;s.lastDaily='';localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  await evalJs("SrokGame.act('daily'); SrokGame.act('trip','tonle_sap')");
  assert((await evalJs('SrokGame.getState().coins'))===330,'Daily reward or free trip failed');
  await evalJs('Date.now=()=>new Date().getTime()+100000');
  await evalJs("SrokGame.act('collectTrip')");
  assert((await evalJs('SrokGame.getState().visits.tonle_sap'))===1,'Trip collection failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.inventory.pepper=2;s.inventory.crab=1;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  await evalJs("SrokGame.act('cook','pepper_crab')");
  assert((await evalJs('SrokGame.getState().cookedKinds.pepper_crab'))===1,'Regional recipe failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.journeyChapter=3;s.visits={tonle_sap:2,kep:2,kampong_speu:2,mondulkiri:2};s.stats.trips=8;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert(await evalJs('SrokGame.journeyComplete()'),'Journey goal did not register');
  await evalJs("SrokGame.act('journeyClaim')");
  assert((await evalJs('SrokGame.getState().journeyWon'))===true,'River celebration failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.xp=650;s.coins=1000;s.fishAt=0;s.plots[0]=null;s.travel=null;s.upgrades=[];s.inventory.rice=2;s.inventory.fish=1;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  const fishBefore=await evalJs('SrokGame.getState().inventory.fish');
  await evalJs("SrokGame.act('upgrade','net'); SrokGame.act('fishPanel'); SrokGame.act('fishCast')");
  await evalJs('Date.now=()=>new Date().getTime()+120000');
  await evalJs("SrokGame.act('fishCatch')");
  await completeFish();
  assert((await evalJs('SrokGame.getState().inventory.fish'))===fishBefore+2,'Fishing net upgrade failed');
  await evalJs("SrokGame.act('upgrade','irrigation'); SrokGame.act('plot','0')");
  assert((await evalJs('SrokGame.getState().plots[0].at-Date.now()'))<20000,'Irrigation upgrade failed');
  await evalJs("SrokGame.act('upgrade','cart'); SrokGame.act('trip','kep')");
  assert((await evalJs('SrokGame.getState().travel.at-Date.now()'))<54000,'Travel cart upgrade failed');
  const porridgeBefore=await evalJs('SrokGame.getState().inventory.porridge || 0');
  await evalJs("SrokGame.act('upgrade','stove'); SrokGame.act('cook','porridge')");
  assert((await evalJs('SrokGame.getState().inventory.porridge'))===porridgeBefore+2,'Clay stove upgrade failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.version=3;s.coins=1000;s.xp=650;s.inventory.rice=8;s.inventory.fish=3;s.plots=s.plots.slice(0,12);delete s.workshop;delete s.craftedKinds;delete s.friendship;delete s.giftAt;delete s.makersChapter;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert((await evalJs('SrokGame.getState().version'))===9,'Version 1.1 save migration failed');
  await evalJs("SrokGame.act('expand'); SrokGame.act('expand')");
  assert((await evalJs('SrokGame.getState().plots.length'))===20,'Field expansion failed');
  await evalJs("SrokGame.act('craft','rice_flour')");
  assert((await evalJs('SrokGame.getState().workshop.id'))==='rice_flour','Workshop start failed');
  await evalJs('Date.now=()=>new Date().getTime()+50000');
  await evalJs("SrokGame.act('collectCraft')");
  assert((await evalJs('SrokGame.getState().craftedKinds.rice_flour'))===1,'Workshop collection failed');
  await evalJs("SrokGame.act('gift','dara')");
  assert((await evalJs('SrokGame.getState().friendship.dara'))===1,'Friendship gift failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.inventory.cotton=3;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  await evalJs("SrokGame.act('craft','krama')");
  await evalJs('Date.now=()=>new Date().getTime()+100000');
  await evalJs("SrokGame.act('collectCraft')");
  assert((await evalJs('SrokGame.getState().craftedKinds.krama'))===1,'Krama crafting failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.makersChapter=2;s.stats.crafted=10;s.stats.gifts=10;s.friendship.dara=10;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert(await evalJs('SrokGame.makersComplete()'),'Makers goal did not register');
  await evalJs("SrokGame.act('makersClaim')");
  assert((await evalJs('SrokGame.getState().makersWon'))===true,'Makers fair ending failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.decor=['flowers'];s.decorPositions={flowers:{x:340,y:345}};localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert(await evalJs('document.querySelector(".map-decoration").style.left==="340px"'),'Saved decoration position missing');
  assert((await evalJs('SrokGame.getState().mapCamera.zoom'))>1,'Saved map zoom was lost');
  await evalJs("SrokGame.act('arrange'); document.querySelector('.map-decoration').click()");
  assert(await evalJs('document.querySelector(".map-decoration").classList.contains("selected")'),'Decoration selection failed');
  await evalJs(`(()=>{const v=document.querySelector('#farm-map'),r=v.getBoundingClientRect();document.querySelector('#map-world').dispatchEvent(new MouseEvent('click',{bubbles:true,clientX:r.left+60,clientY:r.top+90}))})()`);
  assert((await evalJs('SrokGame.getState().decorPositions.flowers.x'))!==340,'Decoration placement failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.xp=400;s.coins=600;s.chicken=false;s.inventory.corn=2;s.fishAt=0;s.stats.miniGames=0;s.miniBest={};localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  await evalJs("SrokGame.act('animalPanel','coop'); SrokGame.act('coop'); SrokGame.act('feedAnimal')");
  assert((await evalJs('SrokGame.getState().animalCare.chicken'))===1,'Chicken care failed');
  await evalJs('Date.now=()=>new Date().getTime()+120000');
  await evalJs("SrokGame.act('coop')");
  assert((await evalJs('SrokGame.getState().inventory.egg'))>=3,'Animal care bonus failed');
  await evalJs("SrokGame.act('fishPanel'); SrokGame.act('fishCast')");
  await evalJs('Date.now=()=>new Date().getTime()+123000');
  await evalJs("SrokGame.act('fishCatch')");
  await completeFish();
  assert((await evalJs('SrokGame.getState().inventory.fish'))>=1,'Fishing interaction failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.stats.miniGames=0;s.miniBest={};localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  const riceBefore=await evalJs('SrokGame.getState().inventory.rice || 0');
  await evalJs("SrokGame.act('tab','farm'); SrokGame.act('openMini','rice'); document.querySelector('.mini-rice-tile.young').click()");
  for(let i=0;i<9;i++)await evalJs("document.querySelector('.mini-rice-tile.ripe:not(:disabled)').click()");
  assert((await evalJs('SrokGame.getState().inventory.rice'))===riceBefore+1,'Rice sorting reward or mistake handling failed');
  assert((await evalJs('SrokGame.getState().stats.miniGames'))===1,'Rice sorting completion not recorded');
  await evalJs("SrokGame.act('close'); SrokGame.act('openMini','rice')");
  assert((await evalJs('document.querySelector(".mini-rice-grid")===null')),'Rice sorting cooldown failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.inventory.cotton=3;s.workshop=null;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  const kramaBefore=await evalJs('SrokGame.getState().inventory.krama || 0');
  await evalJs("SrokGame.act('tab','kitchen'); SrokGame.act('kitchenMode','workshop'); SrokGame.act('openMini','loom')");
  for(let i=0;i<4;i++)await evalJs("(()=>{const target=document.querySelector('.mini-stripe.current');const tone=['clay','gold','indigo'].find(x=>target.classList.contains(x));document.querySelector('.mini-color.'+tone).click()})()");
  assert((await evalJs('SrokGame.getState().inventory.krama'))===kramaBefore+1,'Krama weaving reward failed');
  assert((await evalJs('SrokGame.getState().inventory.cotton'))===0,'Krama weaving did not consume cotton');
  const coinsBefore=await evalJs('SrokGame.getState().coins');
  await evalJs("SrokGame.act('tab','market'); SrokGame.act('openMini','market')");
  for(let i=0;i<3;i++)await evalJs("(()=>{const target=document.querySelector('.mini-market-product').previousElementSibling.querySelector('b').textContent;document.querySelector('.mini-basket[data-id=\"'+target+'\"]').click()})()");
  assert((await evalJs('SrokGame.getState().coins'))===coinsBefore+15,'Market basket reward failed');
  assert((await evalJs('SrokGame.getState().stats.miniGames'))===3,'Mini game completions were not recorded');
  assert((await evalJs('SrokGame.getState().miniAt.market'))>Date.now(),'Mini game cooldown was not saved');
  const lotusBefore=await evalJs('SrokGame.getState().inventory.lotus || 0');
  await evalJs("SrokGame.act('close'); SrokGame.act('tab','farm'); SrokGame.act('openMini','lotus')");
  await evalJs(`(()=>{for(let i=0;i<6;i++){let cards=document.querySelectorAll('.mini-memory-card');if(!cards[i])break;if(cards[i].classList.contains('matched'))continue;cards[i].click();for(let j=i+1;j<6;j++){cards=document.querySelectorAll('.mini-memory-card');if(!cards[i]||!cards[j])break;if(cards[j].classList.contains('matched'))continue;cards[j].click();cards=document.querySelectorAll('.mini-memory-card');if(!cards[i]||cards[i].classList.contains('matched'))break;cards[i].click();}}})()`);
  assert((await evalJs('SrokGame.getState().inventory.lotus'))===lotusBefore+1,'Pond pairs reward failed');
  const canalCoins=await evalJs('SrokGame.getState().coins');
  await evalJs("SrokGame.act('close'); SrokGame.act('openMini','canal')");
  await evalJs(`(()=>{for(let i=0;i<4;i++){for(let turn=0;turn<3;turn++){const gate=document.querySelector('.mini-canal-gate[data-id="'+i+'"]');if(!gate||gate.classList.contains('aligned'))break;gate.click();}}})()`);
  assert((await evalJs('SrokGame.getState().coins'))===canalCoins+8,'Water channel reward failed');
  assert((await evalJs('SrokGame.getState().stats.miniGames'))===5,'Five mini games were not recorded');
  const bananasBefore=await evalJs('SrokGame.getState().inventory.banana || 0');
  await evalJs("SrokGame.act('close'); SrokGame.act('farmMode','games'); SrokGame.act('openMini','cargo')");
  assert(await evalJs('!!document.querySelector(".mini-cargo-basket")'),'Cargo game did not open from Games hub');
  await evalJs(`(()=>{for(let i=0;i<30;i++){const basket=document.querySelector('.mini-cargo-basket[data-id="1"]');if(!basket)break;basket.click()}})()`);
  assert((await evalJs('SrokGame.getState().inventory.banana || 0'))>bananasBefore,'Boat cargo did not award bananas');
  const herbBefore=await evalJs('SrokGame.getState().inventory.lemongrass || 0');
  await evalJs("SrokGame.act('close'); SrokGame.act('openMini','recipe')");
  await evalJs(`(()=>{for(let i=0;i<30;i++){const options=document.querySelectorAll('.mini-recipe-option');if(!options.length)break;options[i%options.length].click()}})()`);
  assert((await evalJs('SrokGame.getState().inventory.lemongrass || 0'))===herbBefore+1,'Recipe game did not award lemongrass');
  assert((await evalJs('SrokGame.getState().stats.miniGames'))===7,'Seven hub games were not recorded');
  await evalJs(`(()=>{const s=SrokGame.getState();s.coins=3000;s.xp=650;s.lastDaily='';localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  await evalJs("SrokGame.act('buyProperty','family_home'); SrokGame.act('buyProperty','produce_truck')");
  assert((await evalJs('SrokGame.getState().coins'))===1860,'Property purchase cost failed');
  await evalJs("SrokGame.act('tab','farm')");
  assert((await evalJs('document.querySelectorAll(".map-house.improved,.map-truck").length'))===2,'Bought property is missing from the village map');
  await evalJs("SrokGame.act('daily')");
  assert((await evalJs('SrokGame.getState().coins'))===1910,'Family home daily gift failed');
  const salePrice=await evalJs('SrokGame.getState().inventory.rice');
  await evalJs("SrokGame.act('sell','rice')");
  assert((await evalJs('SrokGame.getState().coins'))===1915,'Produce truck market bonus failed');
  assert((await evalJs('SrokGame.getState().inventory.rice'))===salePrice-1,'Market sale did not remove goods');
  await evalJs(`(()=>{const s=SrokGame.getState();localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  assert((await evalJs('SrokGame.getState().ownedProperty.length'))===2,'Property was not saved');
  await evalJs(`(()=>{const s=SrokGame.getState();SrokSave.save('srok-srae-save-v2',s);localStorage.setItem('srok-srae-save-v2','{broken');location.reload()})()`);
  await waitForGame();
  assert((await evalJs('SrokGame.getState().inventory.egg'))>=3,'Corrupt save recovery failed');
  assert((await evalJs('SrokGame.getState().stats.miniGames'))===7,'Mini game progress was lost during recovery');
  assert((await evalJs('SrokGame.getState().miniAt.market'))>Date.now(),'Saved mini game cooldown was lost');
  assert((await evalJs('SrokGame.getState().ownedProperty.length'))===2,'Property was lost during recovery');
  assert((await evalJs('SrokGame.getState().miniBest.cargo'))>=1,'Best game rating was lost during recovery');
  await evalJs(`(()=>{const s=SrokGame.getState();s.coins=5000;s.xp=2000;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  await evalJs("SrokGame.act('buyProperty','storage_house'); SrokGame.act('buyProperty','rice_mill'); SrokGame.act('buyProperty','market_stall'); SrokGame.act('buyProperty','produce_motorbike')");
  assert((await evalJs('SrokGame.getState().ownedProperty.length'))===6,'New property purchases failed');
  assert((await evalJs('document.querySelectorAll(".map-owned").length'))>=3,'New properties are missing from map');
  await evalJs(`(()=>{const s=SrokGame.getState();s.lastDaily='';localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  const giftRice=await evalJs('SrokGame.getState().inventory.rice || 0');
  await evalJs("SrokGame.act('daily')");
  assert((await evalJs('SrokGame.getState().inventory.rice'))===giftRice+4,'Grain store daily gift failed');
  const flourBefore=await evalJs('SrokGame.getState().inventory.rice_flour || 0');
  await evalJs("SrokGame.act('craft','rice_flour')");
  await evalJs('Date.now=()=>new Date().getTime()+200000');
  await evalJs("SrokGame.act('collectCraft')");
  assert((await evalJs('SrokGame.getState().inventory.rice_flour || 0'))===flourBefore+2,'Rice mill production bonus failed');
  await evalJs(`(()=>{const s=SrokGame.getState(),o=s.orders[0];for(const [id,n] of Object.entries(o.needs))s.inventory[id]=n;localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  const deliveryBase=await evalJs('(()=>{const s=SrokGame.getState();return {coins:s.coins,xp:s.xp,order:s.orders[0]}})()');
  await evalJs(`SrokGame.act('deliver','${deliveryBase.order.id}')`);
  const deliveryState=await evalJs('SrokGame.getState()');
  assert(deliveryState.coins-deliveryBase.coins===deliveryBase.order.coins+10&&deliveryState.xp-deliveryBase.xp===deliveryBase.order.xp+4,'Market stall or motorbike order bonus failed');
  await evalJs(`(()=>{const s=SrokGame.getState();s.inventory.rice=Math.max(5,s.inventory.rice||0);localStorage.setItem('srok-srae-save-v2',JSON.stringify(s));location.reload()})()`);
  await waitForGame();
  const marketRice=await evalJs('SrokGame.getState().inventory.rice || 0');
  await evalJs("SrokGame.act('tab','market'); SrokGame.act('sellPanel','rice')");
  assert(await evalJs('!!document.querySelector(".sale-options")'),'Batch sale dialog missing');
  await evalJs("SrokGame.act('sellQty','all')");
  assert((await evalJs('SrokGame.getState().inventory.rice || 0'))===0,'Batch sale did not clear stock');
  assert(marketRice>0,'No rice available for market test');
  console.log('PASS: migration, farming, journeys, workshop, animal care, item-earning fishing, seven hub games, six properties, batch sales, save recovery, three endings');
} finally {
  if(ws)ws.close();
  processChrome.kill();
  if(profile.startsWith(os.tmpdir()+path.sep))await rm(profile,{recursive:true,force:true,maxRetries:3,retryDelay:150});
}
